services:
  jakes-app-bases:
    build: .
    container_name: jakes-app-bases
    ports:
      - '3007:3000'
    volumes:
      - /root/jakes-app-bases-data:/data
    environment:
      - NODE_ENV=production
      - JWT_SECRET=jakes-app-bases-preview-2026
    restart: unless-stopped
